# Generated by Django 3.2.5 on 2021-07-14 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(max_length=150, null=True)),
                ('impactFaible', models.CharField(max_length=150, null=True)),
                ('impactMoyen', models.CharField(max_length=150, null=True)),
                ('impactFort', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoteImpact', models.IntegerField(null=True)),
                ('NoteOcc', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actifCritique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actif.actifcritique')),
                ('impact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impact.impact')),
            ],
        ),
        migrations.AddField(
            model_name='impact',
            name='typeImpact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impact.typeimpact'),
        ),
    ]
