# Generated by Django 3.2.3 on 2021-10-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menace', '0002_alter_menace_type'),
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactnote',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='impactnote',
            name='id',
        ),
        migrations.AddField(
            model_name='impactnote',
            name='menace',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menace.menace'),
            preserve_default=False,
        ),
    ]
