# Generated by Django 3.2.3 on 2021-10-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actifcritique',
            name='etat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
