# Generated by Django 3.2.3 on 2021-10-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actif', '0002_actif_intervenants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actif',
            old_name='intervenants',
            new_name='intervenant',
        ),
    ]
