# Generated by Django 3.2.3 on 2021-10-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='debut',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
