# Generated by Django 3.2.5 on 2021-07-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('reference', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('acces', models.CharField(max_length=150)),
                ('acteur', models.CharField(max_length=150)),
                ('motivation', models.CharField(max_length=150)),
                ('resultat', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
