# Generated by Django 3.2.5 on 2021-10-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menace',
            name='type',
            field=models.CharField(choices=[('HR', 'Acteur Humain & Access réseau'), ('HP', 'Acteur Humain & Access physique'), ('PS', 'Problèmes systèmes'), ('AP', 'Autres Problèmes')], max_length=50, null=True),
        ),
    ]
