# Generated by Django 3.2.3 on 2021-10-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actif', '0003_rename_intervenants_actif_intervenant'),
        ('menace', '0002_alter_menace_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menace',
            name='actif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actif.actifcritique'),
        ),
    ]
