# Generated by Django 3.2.5 on 2021-10-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('etat', models.CharField(max_length=50, null=True)),
                ('note', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif_critique', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actif.actifcritique')),
            ],
        ),
    ]
