# Generated by Django 3.2.5 on 2021-07-14 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actif', '0001_initial'),
        ('menace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeVulnerabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menace.menace')),
                ('typeVulnerabilite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vulnerabilite.typevulnerabilite')),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabiliteNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('actifCritique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actif.actifcritique')),
                ('vulnerabilite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vulnerabilite.vulnerabilite')),
            ],
        ),
    ]
