# Generated by Django 3.2.5 on 2021-10-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilite',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerabilite',
            name='menace',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
