# Generated by Django 3.2.3 on 2021-10-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilite', '0002_auto_20211007_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilite',
            name='menace',
        ),
    ]
